export const LOAD_CONTACTS_SUCCESS = "LOAD_CONTACTS_SUCCCESS";

export const ADD_CONTACTS_SUCCESS = "ADD_CONTACTS_SUCCESS";

export const EDIT_CONTACTS_SUCCESS = "EDIT_CONTACTS_SUCCESS";

export const DELETE_CONTACTS_SUCCESS = "DELETE_CONTACTS_SUCCESS";